# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18_C7USQcK6P9dUq59M3f4x0A3eqZbeXj
"""

!mkdir -p batch-monitoring-simulator/logs
!mkdir -p batch-monitoring-simulator/incidents

log_content = """2026-03-01 15:30:01 INFO Job PAYMENT_IMPORT started
2026-03-01 15:30:10 INFO Job PAYMENT_IMPORT finished SUCCESS
2026-03-01 15:31:02 INFO Job REPORT_GENERATION started
2026-03-01 15:31:30 ERROR Job REPORT_GENERATION failed TIMEOUT
2026-03-01 15:32:00 ALERT Disk usage above threshold
"""

with open("batch-monitoring-simulator/logs/batch.log", "w") as f:
    f.write(log_content)

import json
from datetime import datetime

LOG_FILE = "batch-monitoring-simulator/logs/batch.log"
INCIDENT_FILE = "batch-monitoring-simulator/incidents/incidents.json"

ERROR_KEYWORDS = ["ERROR", "ALERT"]


def read_logs():
    with open(LOG_FILE, "r") as file:
        return file.readlines()


def detect_incidents(lines):
    incidents = []

    for line in lines:
        if any(keyword in line for keyword in ERROR_KEYWORDS):
            incidents.append({
                "timestamp": datetime.now().isoformat(),
                "event": line.strip(),
                "status": "OPEN"
            })

    return incidents


def save_incidents(incidents):
    try:
        with open(INCIDENT_FILE, "r") as file:
            existing = json.load(file)
    except:
        existing = []

    existing.extend(incidents)

    with open(INCIDENT_FILE, "w") as file:
        json.dump(existing, file, indent=4)


logs = read_logs()
incidents = detect_incidents(logs)

if incidents:
    print("Incidentes detectados:")
    for i in incidents:
        print(i["event"])

    save_incidents(incidents)
    print("Incidente registrado.")
else:
    print("Sistema saudável.")